server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks
    password: postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

stock-service:
  stocks-topic-name: stocks
